### ISSUE TITLE
[Feature Request] Expose open ports on devbox.sh

### ISSUE THREAD

**Issue by mikenikles** [jetify-com/devbox#1023]
As a developer who works on a project with devbox.sh,
I want to access (web) applications at a URL such as `github-com-owner-repo-branch-port.devbox.sh`
so that I can review code changes.

## Notes

* It is important this is a single sub-domain. Auth providers such as Auth0 and WorkOS have restrictions on their redirect URLs which allows for wildcards, but not multiple sub-domains.
* [stretch goal] Require authentication for these URLs by default, but allow developers to mark ports as public. For web apps, this allows developers to run linters (SEO, a11y, Lighthouse, etc.) against their development environment.

**Comment by LucilleH** [comment]
Thanks for the suggestion!

Right now we allow users to create multiple projects with the same owner/repo/branch/folder combination. It would be slightly trickier to get this working properly unless we make some assumption - eg. the user will only have 1 project with such combination, or pick the first project that matches such combination.

**Comment by Lagoja** [comment]
This feature is available via the `Preview` button on Jetify Devspaces. Closing since we've moved `devbox.sh` to Devspaces
