### ISSUE TITLE
[Improvement] `devbox run` should not run init_hooks if they have already run

### ISSUE THREAD

**Issue by Lagoja** [jetify-com/devbox#1090]
**Problem:** Every time a devbox script is executed, we run the plugin and user init_hooks. This means that if a script is run inside a `devbox shell`, or if a script is called by another devbox script, the init_hook will run multiple times. This can cause issues if an init_hook is not designed to be run multiple times, or if the init_hook takes a long time to resolve

**Proposed Solution:** _init_hooks_ should only execute once per devbox shell or shellenv.

**Comment by Lagoja** [comment]
cc @LucilleH

**Comment by hezhizhen** [comment]
How about using the env to see if it's in a devbox shell? If so, do not run init_hooks again.

**Comment by LucilleH** [comment]
This is maybe a little trickier than it appears to be. Following scenarios I'm thinking about:
1. A user is in a devbox shell of a project, and then decides to cd into another project to run a devbox script
2. A user has devbox global enabled, and added `devbox global shellenv` to their `.rc` files

So in a sense this is for init hooks that are not designed to be run twice, but different init hooks should be able to run at least once (from different projects, local vs global, etc). I don't know how this can be done without some sort of init hook content hashing and set special env variable for that hash.

Thoughts?

**Comment by Lagoja** [comment]
Resolved in newer versions of Devbox
