### ISSUE TITLE
[Bug]: `gem install psych` fails

### ISSUE THREAD

**Issue by CorbanR** [jetify-com/devbox#1543]
**Current Behavior (bug)**
1. `devbox init`
2. `devbox generate direnv`
3. `devbox add ruby libyaml libxml2 xmlsec`
4. `gem install bundler` <-- works
5. `gem install nokogiri` <-- works (it uses libxml2 appropriately)
6. `gem install psych` <-- FAILS

When I install gems using my old flake shell (Example)
```
{
  description = "Ruby Environment for test blog dog";
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    flake-compat.url = "github:edolstra/flake-compat";
    flake-compat.flake = false;
  };

  outputs = {
    self,
    nixpkgs,
    flake-utils,
    ...
  } @ inputs:
  flake-utils.lib.eachDefaultSystem
  (
    system: let
      pkgs = nixpkgs.legacyPackages.${system};
      inherit (pkgs.darwin.apple_sdk.frameworks) CoreServices ApplicationServices Security;
      darwin_packages = [ CoreServices ApplicationServices Security];
      ruby = pkgs.ruby_3_2;

    in rec {
      devShells.default = pkgs.mkShell {
        packages = with pkgs; [
          autoconf
          automake
          bash-completion
          bison
          cairo
          coreutils
          gdbm
          git
          gnumake
          groff
          libffi
          libiconv
          libtool
          libunwind
          libxml2
          libxslt
          libyaml
          msgpack
          ncurses
          netcat
          openssl
          pkg-config
          readline
          ruby
          shared-mime-info # Required for the gem
          sqlcipher
          sqlite
          sqlite-interactive
          swagger-codegen3
          zlib
        ] ++ darwin_packages;
        shellHook = ''
          export FREEDESKTOP_MIME_TYPES_PATH=${pkgs.shared-mime-info}/share/mime/packages/freedesktop.org.xml

          mkdir -p .gems
          export GEM_HOME=$PWD/.gems
          export GEM_PATH=$GEM_HOME
          export PATH=$GEM_HOME/bin:$PATH

          # Add additional folders to to XDG_DATA_DIRS if they exists, which will get sourced by bash-completion
          for p in ''${buildInputs}; do
            if [ -d "$p/share/bash-completion" ]; then
              if [ -z ''${XDG_DATA_DIRS} ]; then
                XDG_DATA_DIRS="$p/share"
              else
                XDG_DATA_DIRS="$XDG_DATA_DIRS:$p/share"
              fi
            fi
          done
        '';
      };
    }
    );
  }
```
Everything works as expected and I can install psych. I'm not sure if this is an issue with devbox or not, but I belive it should be as easy as `devbox install libyaml` followed by `gem install psych` just like `gem install nokogiri` worked 

**Expected Behavior (fix)**
`gem install psych` should just work 

**Additional context**
devbox version -v
Version:     0.6.0
Platform:    darwin_arm64
Commit:      fdbd72f230b3520dde60d72c57d9460922ade656
Commit Time: 2023-10-03T18:04:08Z
Go Version:  go1.21.1
Launcher:    0.2.0

```
cat devbox.json
{
  "packages": [
    "ruby@latest",
    "libyaml@latest",
    "libxml2@latest",
    "xmlsec@latest"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

**Comment by Lagoja** [comment]
Hey, thanks for reporting! `gem install psych` worked on my darwin_arm64 machine. Can you share more details about the error message you saw?

**Comment by CorbanR** [comment]
Sure, in a fresh environment using the commands I stated above, it appears like it can't find the library `libyaml` library. However i'm confused because initially I got the same error with `nokogiri` but adding the `libxml2` package seems to have fixed it. 

**Here is the error** 
```
 gem install psych
Fetching psych-5.1.0.gem
Building native extensions. This could take a while...
ERROR:  Error installing psych:
	ERROR: Failed to build gem native extension.

    current directory: /private/tmp/fool/.devbox/virtenv/ruby/gems/psych-5.1.0/ext/psych
/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/bin/ruby extconf.rb
checking for yaml.h... no
yaml.h not found
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/bin/$(RUBY_BASE_NAME)
	--with-libyaml-source-dir
	--without-libyaml-source-dir
	--with-yaml-0.1-dir
	--without-yaml-0.1-dir
	--with-yaml-0.1-include
	--without-yaml-0.1-include=${yaml-0.1-dir}/include
	--with-yaml-0.1-lib
	--without-yaml-0.1-lib=${yaml-0.1-dir}/lib
	--with-yaml-0.1-config
	--without-yaml-0.1-config
	--with-pkg-config
	--without-pkg-config
	--with-libyaml-dir
	--without-libyaml-dir
	--with-libyaml-include
	--without-libyaml-include=${libyaml-dir}/include
	--with-libyaml-lib
	--without-libyaml-lib=${libyaml-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /private/tmp/fool/.devbox/virtenv/ruby/extensions/arm64-darwin-22/3.2.0/psych-5.1.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /private/tmp/fool/.devbox/virtenv/ruby/gems/psych-5.1.0 for inspection.
Results logged to /private/tmp/fool/.devbox/virtenv/ruby/extensions/arm64-darwin-22/3.2.0/psych-5.1.0/gem_make.out```

**mkmf.log shows** 
```
package configuration for yaml-0.1 is not found
find_header: checking for yaml.h... -------------------- no

DYLD_FALLBACK_LIBRARY_PATH=.:/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/lib "clang -o conftest -I/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/include/ruby-3.2.0/arm64-darwin22 -I/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/include/ruby-3.2.0/ruby/backward -I/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/include/ruby-3.2.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wextra-tokens -Wdeprecated-declarations -Wdivision-by-zero -Wdiv-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wundef  -fno-common -pipe conftest.c  -L. -L/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/lib -L. -fstack-protector-strong     -lruby-3.2.2  -lpthread  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

DYLD_FALLBACK_LIBRARY_PATH=.:/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/lib "clang -I/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/include/ruby-3.2.0/arm64-darwin22 -I/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/include/ruby-3.2.0/ruby/backward -I/nix/store/1v7fqs5ihrp6l44sncsji32c64ldgsvy-ruby-3.2.2/include/ruby-3.2.0 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wextra-tokens -Wdeprecated-declarations -Wdivision-by-zero -Wdiv-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wundef  -fno-common -pipe   -c conftest.c"
conftest.c:3:10: fatal error: 'yaml.h' file not found
#include <yaml.h>
         ^~~~~~~~
1 error generated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <yaml.h>
/* end */

--------------------

```

**Comment by halochou** [comment]
I had the same issue. It seems `devbox add libyaml` did not install libyaml header files which is in its `dev` output.

**Comment by CorbanR** [comment]
Is this a bug in how `devbox` installs `libyaml` then?

**Comment by flype** [comment]
Yes, I'm running into the exact same issue here seems libyaml it's not installing correctly the headers file

**Comment by flype** [comment]
I've found a workaround. 

Seems the issue it's introduced in this change: https://github.com/NixOS/nixpkgs/commit/28b782e58dd18f3e97deb9b97c3517ad409c0407 

The libyaml package is a [split package](http://nixos.org/nixpkgs/manual/#chap-multiple-output), so it has multiple outputs.

In this case the `out` output has the libraries, and the `dev` output has the headers. Normally the `dev` output is not installed to the user environment when you use the standard install command. But it is used internally when the package is a build dependency of another package.

So if we use the parent commit and manually pinning a Nixpkg commit for the package we can install and compile the gem normally:
```
"packages": [ 
  "github:nixos/nixpkgs/0e5b6eaeea58f7bcf129845f377b449bbd05538b#libyaml"
]
```

```
❯ gem install psych
Building native extensions. This could take a while...
Successfully installed psych-5.1.1.1
Parsing documentation for psych-5.1.1.1
Installing ri documentation for psych-5.1.1.1
Done installing documentation for psych after 0 seconds
1 gem installed
```

I guess this is a common issue in more libs, is there a better way to handle a situation like this? should we make the install command supporting the overwrite of the output in the flake?

**Comment by savil** [comment]
@gcurtis is working on enabling Devbox users to specify multiple outputs from the nix packages. I think that should help resolve this problem.

**Comment by mustela** [comment]
Im having a similar when running ` gem install libxml-ruby`, and Im not really sure how to deal with it. Ive tried the workaround described above, but no luck.  This is the output

```
❯ gem install libxml-ruby
Fetching libxml-ruby-4.1.2.gem
Building native extensions. This could take a while...
ERROR:  Error installing libxml-ruby:
	ERROR: Failed to build gem native extension.

    current directory: /Users/my-user/sites/yay/papi/.devbox/virtenv/ruby/gems/libxml-ruby-4.1.2/ext/libxml
/nix/store/5r97pd7r10b8m4149rp0frny22vla9sj-ruby-3.0.6/bin/ruby extconf.rb
checking for libxml/xmlversion.h in /opt/include/libxml2,/opt/local/include/libxml2,/opt/homebrew/opt/libxml2/include/libxml2,/usr/local/include/libxml2,/usr/include/libxml2,/usr/local/include,/usr/local/opt/libxml2/include/libxml2... no
checking for xmlParseDoc() in -lxml2... no
checking for xmlParseDoc() in -llibxml2... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/nix/store/5r97pd7r10b8m4149rp0frny22vla9sj-ruby-3.0.6/bin/$(RUBY_BASE_NAME)
	--with-xml2-config
	--without-xml2-config
	--with-xml2-dir
	--without-xml2-dir
	--with-xml2-include
	--without-xml2-include=${xml2-dir}/include
	--with-xml2-lib
	--without-xml2-lib=${xml2-dir}/lib
	--with-xml2lib
	--without-xml2lib
	--with-libxml2-dir
	--without-libxml2-dir
	--with-libxml2-include
	--without-libxml2-include=${libxml2-dir}/include
	--with-libxml2-lib
	--without-libxml2-lib=${libxml2-dir}/lib
	--with-libxml2lib
	--without-libxml2lib
 extconf failure: Cannot find libxml2.

Install the library or try one of the following options to extconf.rb:

  --with-xml2-config=/path/to/xml2-config
  --with-xml2-dir=/path/to/libxml2
  --with-xml2-lib=/path/to/libxml2/lib
  --with-xml2-include=/path/to/libxml2/include


To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/my-user/sites/yay/papi/.devbox/virtenv/ruby/extensions/x86_64-darwin-22/3.0.0/libxml-ruby-4.1.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/my-user/sites/yay/papi/.devbox/virtenv/ruby/gems/libxml-ruby-4.1.2 for inspection.
Results logged to /Users/my-user/sites/yay/papi/.devbox/virtenv/ruby/extensions/x86_64-darwin-22/3.0.0/libxml-ruby-4.1.2/gem_make.out

A new release of RubyGems is available: 3.4.20 → 3.4.22!
Run `gem update --system 3.4.22` to update your installation.
```

My devbox
```json
{
  "packages": [
    "bundler@2.4",
    "ruby@3.0",
    "openssl@latest",
    "rubyPackages_3_0.libxml-ruby@4.1.1",
    "postgresql_12@12.13",
    "libyaml@0.2.5",
    "github:nixos/nixpkgs/0e5b6eaeea58f7bcf129845f377b449bbd05538b#libyaml",
    "xmlsec@1.2.34",
    "libxml2@latest"
  ],
  "shell": {
    "init_hook": [],
    "scripts": {
      "run_test": "ruby -e 'puts \"Hello from Ruby #{RUBY_VERSION}\"'"
    }
  }
}

```

**Comment by t-monaghan** [comment]
@mustela would you mind dropping the mkmf.log here?

**Comment by jay-aye-see-kay** [comment]
I think this issue was resolved in https://github.com/jetpack-io/devbox/releases/tag/0.10.0 with the `Alternate Outputs Support` feature.

Running `devbox add libyaml --outputs out,dev` will add this to `devbox.json` and then `gem install psych` works fine.
```json
{
  "packages": {
    "ruby": "latest",
    "libyaml": {
      "version": "latest",
      "outputs": ["out", "dev"]
    }
  }
}
```

**Comment by seven1m** [comment]
@jay-aye-see-kay's answer is the correct one. This fixed the issue for me. Thanks!

Note: if you get an error saying "Output dev not found", just will need to manually delete the libyaml section from `devbox.lock` so it can be regenerated.

**Comment by trya2l** [comment]
@jay-aye-see-kay your command doesn't work for me. The issue persist with this config

```json
{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.10.7/.schema/devbox.schema.json",
  "packages": {
    "ruby": "latest",
    "libyaml": {
      "version": "latest",
      "outputs": ["out", "dev"]
    }
  },
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

However, I've found a workaround (as I'm not aware of the implication of this command) with `bundler config set --local force_ruby_platform true` as mentioned in https://github.com/nix-community/bundix/issues/88#issuecomment-988799901

**Comment by trya2l** [comment]
Also note that if you're using an existing project look for configuration folders like `.bundle` that could break some gem installations. This was the case for me.

**Comment by savil** [comment]
Will close this issue as `devbox add libyaml --outputs out,dev` should resolve it
