### ISSUE TITLE
[Package Issue Report]: python312Packages.pip missing

### ISSUE THREAD

**Issue by mdomke** [jetify-com/devbox#1640]
The [documentation](https://www.jetpack.io/devbox/docs/devbox_examples/languages/python/#installing-packages-with-pip) of devbox indicates that Python with `pip` should be setup by adapting the snippet with the actual version number of Python 
```
{
    "packages": [
        "python312",
        "python312Packages.pip"
    ],
    "shell": {
        "init_hook": ". $VENV_DIR/bin/activate"
    }
}
```
but the `python312Packages.pip` package does not exist. In fact, no `python312Packages.xxx` [exists at all](https://www.nixhub.io/search?q=python312). Is there a reason why these packages are missing for Python 3.12?

**Comment by Lagoja** [comment]
@mdomke thanks for reporting this. It's not clear to me why those packages do not exist for python312 -- it looks like they were never added or surfaced in the core nixpkgs repo. 

I think a better way to work around this is to use the `pip` binary that is bundled with `python@3.12`. Our current plugin only creates a virtual environment if you explicitly add a `pip` package, but we could make it work with the `python` package as well. I can link a PR once I finish testing this

**Comment by Lagoja** [comment]
Merged now! Will work on getting a release out with this in the next week.

**Comment by savil** [comment]
@Lagoja close task?
