### ISSUE TITLE
[Feature]: Start process-compose gui without restarting processes

### ISSUE THREAD

**Issue by schof0rl** [jetify-com/devbox#1737]
**Is your feature request related to a problem you're trying to solve? Please describe.**
It would be nice, if the services gui could be started separately

**Describe the solution you'd like**
Starting the process-compose separate 

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by Lagoja** [comment]
This should be doable if we update the version of Process Compose we are installing, and add a command to re-attach the TUI to the running services. I can investigate this for an upcoming release. 

Would something like `devbox services status` work as a command to reattach the UI?

**Comment by jay-aye-see-kay** [comment]
Oh nice this is a feature I've been wanting too. Would be very happy to see it add (regardless of naming).

A thought on naming `status` implies something that will print and exit, like `ls` does. `devbox services attach` doesn't sound right at first but does align with what process-compose uses. Maybe `attach-ui`?

**Comment by schof0rl** [comment]
Yes that would be cool 

I am working on a k3s plugin and want to see if the services are good enough- would be happy to share the plugin once it is running nice and smooth

**Comment by Lagoja** [comment]
This is now available in Devbox 0.13.0 via `devbox services attach`, provided that you start your services in the background with `devbox services up -b`.
