### ISSUE TITLE
Disable packages installation while entering a Devbox shell

### ISSUE THREAD

**Issue by dax** [jetify-com/devbox#1882]
### What problem are you trying to solve?

When used with direnv and when regularly switching between branches, Devbox slows down the workflow because it tries to keep the packages in sync with the `devbox.lock` state with a `Ensuring packages are installed.`.

### What solution would you like?

Disabling (with an option to `devbox shell`, `devbox run` and `devbox shellenv`) the automatic installation of packages when `devbox.lock` is not in sync and replacing it with a warning message could be enough in many cases.
Indeed, being out of sync might have no real impact on what we want to achieve. 
For example, switching to a branch to work on some features unrelated to the package not being installed or not with the right version.

**Comment by savil** [comment]
@dax thanks for filing this issue.
To clarify: are you imagining an option that you apply as a one-off when doing `devbox shell/run/shellenv`, or something you want to permanently apply to the code used by direnv in your devbox project's directory?

**Comment by dax** [comment]
@savil what I have in mind would be an option (as an env variable) to permanently disable automatic installation of packages by Devbox.

**Comment by savil** [comment]
#2013 is out in the new 0.10.6 release!
