### ISSUE TITLE
Pass options to process-compose

### ISSUE THREAD

**Issue by fdietze** [jetify-com/devbox#1968]
### What problem are you trying to solve?

The devbox services (process-compose) tui is overwhelming. I just want to see mixed terminal output without the tui.

### What solution would you like?

A way to pass options to process-compose to disable the tui: https://f1bonacc1.github.io/process-compose/tui/?h=tui
```
devbox services up -- -t=false
```

**Comment by Lagoja** [comment]
Options can be passed to process-compose now using `--pc-flags`. See the docs at this page: https://www.jetify.com/docs/devbox/cli_reference/devbox_services_up/
