### ISSUE TITLE
Exec format error

### ISSUE THREAD

**Issue by powerAn2020** [jetify-com/devbox#1969]
### What happened?

![image](https://github.com/jetpack-io/devbox/assets/25736019/e120b002-21e0-443c-b736-ce250caabd59)

### Steps to reproduce

1. OS: WSL1 Ubuntu 22.04.4 LTS
2. devbox add nodejs
3. devbox shell
4. node 

### devbox.json

```jsonc
{
  "$schema":  "https://raw.githubusercontent.com/jetpack-io/devbox/0.10.3/.schema/devbox.schema.json",
  "packages": ["nodejs@21.7.1"],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.10.3

### What system does this bug occur on?

Linux (x86-64)

**Comment by Lagoja** [comment]
I think this is a known issue with WSL 1 + NodeJS, and not with Devbox. https://stackoverflow.com/questions/73616907/how-to-use-node-in-wsl-zsh-exec-format-error-node 

We currently only recommend and support WSL 2. Nix does not work out of the box with WSL 1, and requires a few workarounds to get things working correctly: https://nixos.wiki/wiki/Nix_Installation_Guide#Windows_Subsystem_for_Linux_.28WSL.29

**Comment by powerAn2020** [comment]
Thank you, I will switch to wsl2.
