### ISSUE TITLE
Nixhub.io: broken link to Nix installation page in "Tips" section on package page

### ISSUE THREAD

**Issue by rohanssrao** [jetify-com/devbox#2039]
Example: https://www.nixhub.io/packages/python

![image](https://github.com/jetify-com/devbox/assets/17805516/66f75abf-9b0d-4cf3-966a-506c2821ede5)

The link to Nix is a broken URL: https://nixos.org/manual/nix/stable/installation/installation.html

The URL should be replaced with https://nixos.org/manual/nix/stable/installation/.

**Comment by Lagoja** [comment]
@gcurtis I added you as a reviewer to the PR to fix this

**Comment by Lagoja** [comment]
This is merged, and will be fixed on the next deployment. Thank you for reporting!

**Comment by rohanssrao** [comment]
I think the link broke again. The correct link is now https://nix.dev/manual/nix/2.18/installation/installation.html

**Comment by Lagoja** [comment]
I guess they keep moving it : (, let me update and redeploy
