### ISSUE TITLE
VS Code terminal somehow start devbox shell

### ISSUE THREAD

**Issue by mortum5** [jetify-com/devbox#2120]
### What happened?

Found strange behavior when running VS Code via `code.` in the devbox shell. In each new VS Code window when opening the integrated terminal, it will launch with the devbox shell regardless of the repository directory.

### Steps to reproduce

1. Start devbox shell in first repo
2. Start VS code using `code .` in first repo
3. Open new window and choose another repo
4. Open integrated terminal in VS code

### Devbox version

0.11.0

### What system does this bug occur on?

macOS (Apple Silicon)

**Comment by mohsenari** [comment]
Hi @mortum5 thisnkight be due to Devbox's VSCode extension. You can turn this off by checking off the `Devbox: Auto Shell on Terminal` in vscode settings

**Comment by mortum5** [comment]
Oh, i've forget about this issue. Yeah, this is correct, thank you!
