### ISSUE TITLE
Just learning devbox, docs say installer will install nix, it doesn't.

### ISSUE THREAD

**Issue by bdmorin** [jetify-com/devbox#2184]
https://github.com/jetify-com/devbox/blob/56ba0c1d283648446077e82514e54952ab8d3e9e/docs/app/docs/installing_devbox.mdx?plain=1#L34

The installer only installs devbox, doesn't launch nix package manager on Darwin. I ran it today and

The installer doesn't even mention nix.
```
❯ curl -fsSL https://get.jetify.com/devbox | rg -i nix
(nothing)
```

Thought you should know.

**Comment by savil** [comment]
Thanks for trying Devbox! The devbox binary will install nix if its missing. Please continue using the installed Devbox, and when needed it will prompt you to install nix. Feel free to re-open if that doesn't work for you.
