### ISSUE TITLE
Base Dockerfile add ps(procps) package

### ISSUE THREAD

**Issue by east4ming** [jetify-com/devbox#2188]
### What problem are you trying to solve?

I really need to use the `ps` command in containers. But it's not in the current devbox base image.

### What solution would you like?

https://github.com/jetify-com/devbox/blob/56ba0c1d283648446077e82514e54952ab8d3e9e/internal/devbox/generate/tmpl/DevboxImageDockerfileRootUser#L8
https://github.com/jetify-com/devbox/blob/56ba0c1d283648446077e82514e54952ab8d3e9e/internal/devbox/generate/tmpl/DevboxImageDockerfile#L8

changed to:

```
RUN apt-get update && apt-get install -y bash binutils git xz-utils wget sudo procps && rm -rf /var/lib/apt/lists/*
```

Thanks!

**Comment by apgrucza** [comment]
To keep image size to a minimum, the Devbox image should only include packages needed by Devbox itself.

If you’re extending the base Devbox image using `devbox generate dockerfile`, you can install `ps` in that Dockerfile using `apt-get` or [`devbox global add`](https://www.jetify.com/devbox/docs/devbox_global/).

**Comment by east4ming** [comment]
> To keep image size to a minimum, the Devbox image should only include packages needed by Devbox itself.
> 
> If you’re extending the base Devbox image using `devbox generate dockerfile`, you can install `ps` in that Dockerfile using `apt-get` or [`devbox global add`](https://www.jetify.com/devbox/docs/devbox_global/).

fine, thks
