### ISSUE TITLE
how to revert off 0.12.0 back to 0.11.1?

### ISSUE THREAD

**Issue by justinTM** [jetify-com/devbox#2216]
### What problem are you trying to solve?

I'm frustrated that all of my scripts in all of my projects are broken due to no more `init_hook` invokes inside scripts, introduced in v0.12.0

wondering how to get back to v0.11.0?

### What solution would you like?

one-liner command to replace

**Comment by justinTM** [comment]
**note**: use `devbox global add wget` if you don't have it

then run:
```bash
ASSET=devbox_0.11.1_darwin_arm64.tar.gz && wget "https://github.com/jetify-com/devbox/releases/download/$(echo $ASSET | grep -oP '(\d+\.\d+\.\d+)')/$ASSET" && tar -xzvf "$ASSET" && sudo rm $(which devbox) && sudo mv devbox /usr/local/bin/ && rm "$ASSET" && echo && echo && devbox version
```

**Comment by Lagoja** [comment]
You can also set DEVBOX_USE_VERSION=0.11.0 to pin a specific version.
