### ISSUE TITLE
Add support for fetching private binaries in GitHub

### ISSUE THREAD

**Issue by mikael-lindstrom** [jetify-com/devbox#2223]
### What problem are you trying to solve?

We recently switched to using devbox and it has been working great so far. However we have a few internal cli tools available in GitHub release on private repositories. We would like to download these using `runx` but it currently only supports public repositories.

### What solution would you like?

`pkg/runx` already accepts a GitHub token and use it for the GitHub client so `runx` can already find the correct release and figure out the right asset to download in private repos. However the download module does not use the GitHub token and download the asset from the browser url instead of the api url. 

I have made these changes here [mikael-lindstrom/jetify-com-pkg](https://github.com/mikael-lindstrom/jetify-com-pkg/commit/4bd6545a4539c8fab6853615836f5257af5eec97) and using this to build devbox enables `runx` to download for releases in private repositories as long as `DEVBOX_GITHUB_API_TOKEN` is set.

I'd be happy to push a PR but I don't really understand if I should create the PR against [opensource](https://github.com/jetify-com/opensource) or [pkg](https://github.com/jetify-com/pkg) since the code exists in both repos.

### Alternatives you've considered

I have considered if this could be solved with Nix Flakes but they don't have support for fetching "sources" from GitHub releases in private repositories at this time.

**Comment by savil** [comment]
@mikael-lindstrom this sounds good to me. Thank you for offering to contribute the code change. 

Could you please open the PR against the [opensource](https://github.com/jetify-com/opensource) monorepo in the `pkg/runx` folder? Once that PR is merged, a Github Action will publish it in the [pkg](https://github.com/jetify-com/pkg) repo
