### ISSUE TITLE
Can't figure out how to use Nixpkgs Reference

### ISSUE THREAD

**Issue by SomeoneInBlack1922** [jetify-com/devbox#2231]
I cannot use Nixpkgs Reference provided for each package because i do not understand how it is supposed to be written. Both when i try to write it to shell.nix config file or feed it to nix-shell -p command it tells me that it cannot find a package. And i tried a lot of ways already. And i just can't find any information about those references. All i can find is nix manual book which is called "reference". And i can not find any article for this topic in the manual itself.

I did copy it with a button and were writing it like "nixpkgs/f76ba6..." inside list where i put normal package names.

The shell.nix file
```nix
{ pkgs ? import <nixpkgs> {} }:
  pkgs.mkShell {
    nativeBuildInputs = with pkgs.buildPackages; [ 
        bintools-unwrapped #it works
        0cb2fd7c59fed0cd82ef858cbcbdb552b9a33465 #syntax error
        "0cb2fd7c59fed0cd82ef858cbcbdb552b9a33465" #build input 0cb2fd7c59fed0cd82ef858cbcbdb552b9a33465 does not exist
        "nixpkgs/0cb2fd7c59fed0cd82ef858cbcbdb552b9a33465" #build input nixpkgs/0cb2fd7c59fed0cd82ef858cbcbdb552b9a33465 does not exist
        nixpkgs/0cb2fd7c59fed0cd82ef858cbcbdb552b9a33465 #syntax error
     ];
}
``` 
Normal name "ruby_3_3" for this package works. But those normal names work only up to several versions in past. If i need an old package i will not be able to specify it through a normal name.

nixpkgs is defined: it works both in command line and in import <nixpkgs> {} function.

For now i use devbox. A fine thing. But i still want to understand what is wrong here. I understand you can ultimately blame me for not knowing this. But i still think it is an issue since it gave me several hours of headache. So i hope you could at least give directions to where to look for information. Thank you. And i am sorry if i reported to the wrong channel.

**Comment by savil** [comment]
@SomeoneInBlack1922 I think this issue should be filed with the Nix team or in https://discourse.nixos.org/

**Comment by savil** [comment]
I'm going to close out for now, since its not directly relevant to Devbox. Glad you are able to use Devbox to workaround the problems you encountered with Nix!
