### ISSUE TITLE
How to upgrade nix, which was installed by devbox?

### ISSUE THREAD

**Issue by tatsuya6502** [jetify-com/devbox#2234]
Hi. I installed `devbox` a while ago, and recently upgraded it by `devbox version upgrade`. Today I realized that it does not work anymore as the installed `nix` version is no longer supported.

```console
$ devbox version
0.12.0

$ devbox list

Error: Devbox requires nix of version >= 2.12.0. Your version is {nix 2.11.1 aarch64-darwin
    [x86_64-darwin] [gc signed-caches] /etc/nix/nix.conf [/Users/tatsuya/.config/nix/nix.conf /etc/xdg/nix/nix.conf]
    /nix/store /nix/var/nix }. Please upgrade nix and try again.
```

I believe `nix` was installed by `devbox` at first run, and I have no idea where it is and how to upgrade.

```console
$ which nix
nix not found
```

Can you please tell me how to locate nix and upgrade it?

**Environment**

- devbox 0.12.0
- nix 2.11.1
- macOS Sonoma 14.6.1 (arm64)

**Comment by savil** [comment]
@tatsuya6502 i think you can find the most recent nix upgrade instructions here:
https://nix.dev/manual/nix/2.24/installation/upgrading

**Comment by savil** [comment]
in case `nix` is missing from your PATH, can you check if it is in this location:
```
/nix/var/nix/profiles/default/bin/nix
```

You may need to add that to PATH

**Comment by tatsuya6502** [comment]
@savil — Thank you for the prompt reply! I added `/nix/var/nix/profiles/default/bin/nix` to the PATH and followed the nix upgrade instructions. Now `devbox` is working again.

```console
$ which nix
nix not found

$ export PATH=/nix/var/nix/profiles/default/bin:$PATH

$ which nix
/nix/var/nix/profiles/default/bin/nix

$ sudo nix-env --install --file '<nixpkgs>' --attr nix cacert -I nixpkgs=channel:nixpkgs-unstable
warning: $HOME ('/Users/tatsuya') is not owned by you, falling back to the one defined in the 'passwd' file ('/var/root')
replacing old 'nss-cacert-3.80'
replacing old 'nix-2.11.1'
installing 'nix-2.18.5'
installing 'nss-cacert-3.101.1'
these 4 paths will be fetched (2.06 MiB download, 36.63 MiB unpacked):
...

$ sudo launchctl remove org.nixos.nix-daemon
$ sudo launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist


$ cd $(mktemp -d)
$ devbox init
$ devbox add python@3.10
$ devbox shell

(devbox) ... % python
Python 3.10.14 (main, Mar 19 2024, 21:46:16) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
