### ISSUE TITLE
error installing package path:gcloud#google-cloud-sdk

### ISSUE THREAD

**Issue by srivishnu-sivan** [jetify-com/devbox#2242]
### Package name

gcloud#google-cloud-sdk

### What changes are you requesting?

while doing devbox shell, I'm facing this error

Error: error installing package path:gcloud#google-cloud-sdk
source: nix: command error: nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' path-info 'path:/home/vishnu/Desktop/THIS-SHOULD-GET-COMPLETELY-LEARNT/gcloud#google-cloud-sdk' --json --impure: getting status of '/home/dev/Desktop/THIS-SHOULD-GET-COMPLETELY-LEARNT/gcloud': No such file or directory: exit code 1

**Comment by dexdeadly** [comment]
same issue in WSL 2 Ubuntu 24.04

**Comment by savil** [comment]
As per https://www.jetify.com/devbox/docs/guides/using_flakes/
> You can reference a local Flake using the path: reference

Do you have a local nix flake in the `gcloud` folder ?

**Comment by dexdeadly** [comment]
Yes, this is actually no longer an issue. I was able to reset my state and everything worked after that.

**Comment by Lagoja** [comment]
Closing as unable to repro. If there is more information on the project or the flake used, I can try to debug futher
