### ISSUE TITLE
DevboxDirRoot Template Placeholder Incorrect Directory

### ISSUE THREAD

**Issue by m-dwyer** [jetify-com/devbox#2253]
### What happened?

When using `{{.DevboxDirRoot}}` template placeholder in `create_files` section of a plugin, the file is copied into `devbox.d/` instead of the root of the project where the `devbox.json` resides.

### Steps to reproduce

1. In a new project, create file `./my-plugin/plugin.json`:
```
{
  "name": "my-plugin",
  "version": "0.0.1",
  "description": "Test",
  "packages": [],
  "env": {},
  "shell": {},
  "create_files": {
    "{{.DevboxDirRoot}}/process-compose.yaml": "process-compose.yaml"
  }
}
```
2. Create file `./my-plugin/process-compose.yaml`
3. In the root of the new project, create the following `devbox.json`:
```
{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/main/.schema/devbox.schema.json",
  "include": [
    "path:./my-plugin"
  ],
  "env": {},
  "packages": {}
}
```
4. Run `devbox install`

You will see that the `process-compose.yaml` from the plugin is copied into the `./devbox.d` subdirectory, and not in the project root where the `devbox.json` resides.

### Command

install

### devbox.json

```jsonc
{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/main/.schema/devbox.schema.json",
  "include": [
    "path:./my-plugin"
  ],
  "env": {},
  "packages": {}
}
```

### Devbox version

0.12.0

### Nix version

nix (Nix) 2.20.3

### What system does this bug occur on?

macOS (Apple Silicon)

### Debug logs

time=2024-09-05T15:17:43.658+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/dir.go:22 msg="finding devbox config" path=""
time=2024-09-05T15:17:43.658+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/dir.go:66 msg="finding devbox config" dir=/Users/em.dwyer/src/debezium-test
time=2024-09-05T15:17:43.658+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/dir.go:22 msg="finding devbox config" path=""
time=2024-09-05T15:17:43.658+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/dir.go:66 msg="finding devbox config" dir=/Users/em.dwyer/src/debezium-test
time=2024-09-05T15:17:43.729+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/nix.go:337 msg="nix --version --debug output" out="nix (Nix) 2.20.3\nSystem type: aarch64-darwin\nAdditional system types: x86_64-darwin\nFeatures: gc, signed-caches\nSystem configuration file: /etc/nix/nix.conf\nUser configuration files: /Users/em.dwyer/.config/nix/nix.conf:/etc/xdg/nix/nix.conf\nStore directory: /nix/store\nState directory: /nix/var/nix\nData directory: /nix/store/vdvfdnbfarxf2cm4kxh43i48rv296l09-nix-2.20.3/share\n"
time=2024-09-05T15:17:43.729+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/nix/var/nix/profiles/default/bin/nix
time=2024-09-05T15:17:43.774+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=59950 cmd.code=0 cmd.dur=44.66675ms
time=2024-09-05T15:17:43.774+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/dir.go:22 msg="finding devbox config" path=""
time=2024-09-05T15:17:43.774+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/dir.go:66 msg="finding devbox config" dir=/Users/em.dwyer/src/debezium-test
Info: Ensuring packages are installed.
time=2024-09-05T15:17:43.775+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/plugin/plugin.go:85 msg="creating files for package" pkg="&{ref:{Type:path ID: Path:./my-plugin Owner: Repo: Rev: Ref: Dir: Host: URL:} name:test-plugin pluginDir:/Users/em.dwyer/src/debezium-test}"
time=2024-09-05T15:17:43.775+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/plugin/plugin.go:121 msg="Creating file %q from contentPath: %q" /Users/em.dwyer/src/debezium-test/devbox.d/process-compose.yaml=process-compose.yaml
time=2024-09-05T15:17:43.775+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/plugin/plugin.go:85 msg="creating files for package" pkg="&{ref:{Type:path ID: Path:./my-plugin Owner: Repo: Rev: Ref: Dir: Host: URL:} name:test-plugin pluginDir:/Users/em.dwyer/src/debezium-test}"
time=2024-09-05T15:17:43.776+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/nix.go:80 msg="running print-dev-env cmd" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json path:/Users/em.dwyer/src/debezium-test/.devbox/gen/flake"
⣾ Computing the Devbox environment...
time=2024-09-05T15:17:43.776+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json path:/Users/em.dwyer/src/debezium-test/.devbox/gen/flake" cmd.pat
⣯ Computing the Devbox environment...
time=2024-09-05T15:17:44.394+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json path:/Users/em.dwyer/src/debezium-test/.devbox/gen/flake" cmd.path=
✓ Computed the Devbox environment.
time=2024-09-05T15:17:44.395+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' profile list --profile /Users/em.dwyer/src/debezium-test/.devbox/nix/profile/default --json" cmd.path=/nix/var/nix/profiles/default/bin/nix
time=2024-09-05T15:17:44.445+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' profile list --profile /Users/em.dwyer/src/debezium-test/.devbox/nix/profile/default --json" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=59958 cmd.code=0 cmd.dur=49.229333ms
Finished installing packages.
time=2024-09-05T15:17:44.445+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/dir.go:22 msg="finding devbox config" path=""
time=2024-09-05T15:17:44.445+10:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/dir.go:66 msg="finding devbox config" dir=/Users/em.dwyer/src/debezium-test

**Comment by savil** [comment]
@m-dwyer thanks for flagging this. It appears the docs were outdated for some reason. @Lagoja just pushed an update:
https://github.com/jetify-com/devbox/pull/2254/files

> * `{{ .DevboxProjectDir }}` – points to the root folder of their project, where the user's `devbox.json` is stored.
> * `{{ .DevboxDirRoot }}` - points to `<projectDir>/devbox.d`. This directory is public and added to source control by default.

The `devbox.d` folder is where user-plugin-configs live for users to customize their settings

Going to close out since hopefully this addresses your concern. Do let us know if not.
