### ISSUE TITLE
Nixpkgs Devbox v0.13.0 build failure

### ISSUE THREAD

**Issue by mjgallag** [jetify-com/devbox#2285]
https://nixpkgs-update-logs.nix-community.org/devbox/2024-09-20.log

**Comment by Lagoja** [comment]
Good catch, we're using a newer version of Go than the default in Nixpkgs, so we have to change `buildGoModule` to `buildGo123Module`. I'll update the derivation.

**Comment by Lagoja** [comment]
See https://github.com/NixOS/nixpkgs/pull/343377

**Comment by Lagoja** [comment]
0.13.0 is now in Nixpkgs. 

as of 0.13.2, you can also install Devbox via our Nix flake, to get the latest version as soon as it's released: 

```
nix profile install github:jetify-com/devbox/latest
```
