### ISSUE TITLE
Error run devbox with python 3.10

### ISSUE THREAD

**Issue by filippolmt** [jetify-com/devbox#2289]
### What happened?

Error: There was an error installing nix packages
source: nix: command error: nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json path:/Users/filippomerante/project/test/devbox/.devbox/gen/flake: 1 dependencies of derivation '/nix/store/1y9k16rncpahmigf3armg5zhr7gc082c-nix-shell-env.drv' failed to build: exit code 1

### Steps to reproduce

1. devbox add python@3.10
2. devbox shell

### Command

shell

### devbox.json

```jsonc
{
  "$schema":  "https://raw.githubusercontent.com/jetify-com/devbox/0.13.0/.schema/devbox.schema.json",
  "packages": ["python@3.10"]
}
```

### Devbox version

0.13.0

### Nix version

2.24.7

### What system does this bug occur on?

macOS (Apple Silicon)

### Debug logs

❯ DEVBOX_DEBUG=1 devbox run -- mycrash.sh
time=2024-09-22T21:21:31.454+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-09-22T21:21:31.455+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-09-22T21:21:31.455+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/filippomerante/project/github/test/devbox.json dur=209.291µs
time=2024-09-22T21:21:31.455+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package needs patching" pkg=python mode=auto
time=2024-09-22T21:21:31.455+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-09-22T21:21:31.455+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-09-22T21:21:31.455+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/filippomerante/project/github/test/devbox.json dur=26.25µs
time=2024-09-22T21:21:31.455+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package needs patching" pkg=python mode=auto
time=2024-09-22T21:21:31.502+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/nix.go:337 msg="nix --version --debug output" out="nix (Nix) 2.24.7\nSystem type: aarch64-darwin\nAdditional system types: x86_64-darwin\nFeatures: gc, signed-caches\nSystem configuration file: /etc/nix/nix.conf\nUser configuration files: /Users/filippomerante/.config/nix/nix.conf:/etc/xdg/nix/nix.conf\nStore directory: /nix/store\nState directory: /nix/var/nix\nData directory: /nix/store/7mb1mcpmjphg5bgc8m7m0gxrsshrzsk7-nix-2.24.7/share\n"
time=2024-09-22T21:21:31.502+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/nix/var/nix/profiles/default/bin/nix
time=2024-09-22T21:21:31.536+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=3272 cmd.code=0 cmd.dur=33.849ms
time=2024-09-22T21:21:31.536+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/boxcli/run.go:104 msg="run script" script=mycrash.sh args=[]
time=2024-09-22T21:21:31.536+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-09-22T21:21:31.536+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-09-22T21:21:31.536+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/filippomerante/project/github/test/devbox.json dur=72.208µs
time=2024-09-22T21:21:31.536+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package needs patching" pkg=python mode=auto
time=2024-09-22T21:21:31.536+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package needs patching" pkg=python mode=auto
time=2024-09-22T21:21:31.537+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package needs patching" pkg=python mode=auto
Info: Ensuring packages are installed.
time=2024-09-22T21:21:31.537+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/plugin/plugin.go:85 msg="creating files for package" pkg=python@3.10
time=2024-09-22T21:21:31.537+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/plugin/plugin.go:128 msg="Creating file %q from contentPath: %q" /Users/filippomerante/project/github/test/.devbox/virtenv/python/bin/venvShellHook.sh=python/venvShellHook.sh
time=2024-09-22T21:21:31.537+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package needs patching" pkg=python mode=auto
time=2024-09-22T21:21:31.537+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' path-info --offline --json /nix/store/r26gjy09nhlai4xwxk24v19987mamgvx-python3-3.10.15" cmd.path=/nix/var/nix/profiles/default/bin/nix
time=2024-09-22T21:21:31.581+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' path-info --offline --json /nix/store/r26gjy09nhlai4xwxk24v19987mamgvx-python3-3.10.15" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=3280 cmd.code=0 cmd.dur=43.517292ms
time=2024-09-22T21:21:31.581+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package needs patching" pkg=python mode=auto
time=2024-09-22T21:21:31.581+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/plugin/plugin.go:85 msg="creating files for package" pkg=python310
time=2024-09-22T21:21:31.581+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/plugin/plugin.go:128 msg="Creating file %q from contentPath: %q" /Users/filippomerante/project/github/test/.devbox/virtenv/python/bin/venvShellHook.sh=python/venvShellHook.sh
time=2024-09-22T21:21:31.581+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package needs patching" pkg=python mode=auto
time=2024-09-22T21:21:31.581+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/nix.go:80 msg="running print-dev-env cmd" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json path:/Users/filippomerante/project/github/test/.devbox/gen/flake"
⣾ Computing the Devbox environment...
time=2024-09-22T21:21:31.581+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes
⢿ Computing the Devbox environment...
time=2024-09-22T21:21:33.534+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json path:/Users/filippomerante/project/github/test/.devbox/gen/flake" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.stderr="1 dependencies of derivation '/nix/store/p3cp9f07kj5pc1l6kyjp7fclxfzv4fpm-nix-
✓ Computed the Devbox environment.
Error: error running script "mycrash.sh" in Devbox: nix: command error: nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json path:/Users/filippomerante/project/github/test/.devbox/gen/flake: 1 dependencies of derivation '/nix/store/p3cp9f07kj5pc1l6kyjp7fclxfzv4fpm-nix-shell-env.drv' failed to build: exit code 1

time=2024-09-22T21:21:33.534+02:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:68 msg="command error" stderr="trace: evaluating glibc-patch.packages.aarch64-darwin.python310\nbuilding '/nix/store/62m57fl3nqrflknm7gi5xgjhzlzlkf7s-python3-3.10.15.drv'...\nerror: builder for '/nix/store/62m57fl3nqrflknm7gi5xgjhzlzlkf7s-python3-3.10.15.drv' failed with exit code 1;\n       last 25 log lines:\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:108 msg=\"trying config file\" path=.\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=/private/tmp/devbox.json\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=/private/devbox.json\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=/devbox.json\n       > time=2024-09-22T21:21:33.503+02:00 level=ERROR source=go.jetpack.io/devbox/internal/devconfig/config.go:135 msg=\"config file search error\" err=\"no devbox config file found\" dur=110.042µs\n       > time=2024-09-22T21:21:33.503+02:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/run.go:79 msg=\"failed to open devbox\" err=\"no devbox.json found in the current directory (or any parent directories). Did you run `devbox init` yet?\\ngo.jetpack.io/devbox/internal/boxcli/usererr.New\\n\\tgo.jetpack.io/devbox/internal/boxcli/usererr/usererr.go:30\\ngo.jetpack.io/devbox/internal/devbox.Open\\n\\tgo.jetpack.io/devbox/internal/devbox/devbox.go:84\\ngo.jetpack.io/devbox/internal/boxcli.listScripts\\n\\tgo.jetpack.io/devbox/internal/boxcli/run.go:72\\ngo.jetpack.io/devbox/internal/boxcli.runCmd\\n\\tgo.jetpack.io/devbox/internal/boxcli/run.go:66\\ngo.jetpack.io/devbox/internal/boxcli.globalCmd\\n\\tgo.jetpack.io/devbox/internal/boxcli/global.go:37\\ngo.jetpack.io/devbox/internal/boxcli.RootCmd\\n\\tgo.jetpack.io/devbox/internal/boxcli/root.go:66\\ngo.jetpack.io/devbox/internal/boxcli.Execute\\n\\tgo.jetpack.io/devbox/internal/boxcli/root.go:111\\ngo.jetpack.io/devbox/internal/boxcli.Main\\n\\tgo.jetpack.io/devbox/internal/boxcli/root.go:139\\nmain.main\\n\\t./main.go:11\\nruntime.main\\n\\truntime/proc.go:272\\nruntime.goexit\\n\\truntime/asm_arm64.s:1223\"\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg=\"searching for config file (including parent directories)\" path=.\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=devbox.json\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:108 msg=\"trying config file\" path=.\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=/private/tmp/devbox.json\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=/private/devbox.json\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=/devbox.json\n       > time=2024-09-22T21:21:33.503+02:00 level=ERROR source=go.jetpack.io/devbox/internal/devconfig/config.go:135 msg=\"config file search error\" err=\"no devbox config file found\" dur=37.833µs\n       > time=2024-09-22T21:21:33.503+02:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/run.go:79 msg=\"failed to open devbox\" err=\"no devbox.json found in the current directory (or any parent directories). Did you run `devbox init` yet?\\ngo.jetpack.io/devbox/internal/boxcli/usererr.New\\n\\tgo.jetpack.io/devbox/internal/boxcli/usererr/usererr.go:30\\ngo.jetpack.io/devbox/internal/devbox.Open\\n\\tgo.jetpack.io/devbox/internal/devbox/devbox.go:84\\ngo.jetpack.io/devbox/internal/boxcli.listScripts\\n\\tgo.jetpack.io/devbox/internal/boxcli/run.go:72\\ngo.jetpack.io/devbox/internal/boxcli.runCmd\\n\\tgo.jetpack.io/devbox/internal/boxcli/run.go:66\\ngo.jetpack.io/devbox/internal/boxcli.RootCmd\\n\\tgo.jetpack.io/devbox/internal/boxcli/root.go:75\\ngo.jetpack.io/devbox/internal/boxcli.Execute\\n\\tgo.jetpack.io/devbox/internal/boxcli/root.go:111\\ngo.jetpack.io/devbox/internal/boxcli.Main\\n\\tgo.jetpack.io/devbox/internal/boxcli/root.go:139\\nmain.main\\n\\t./main.go:11\\nruntime.main\\n\\truntime/proc.go:272\\nruntime.goexit\\n\\truntime/asm_arm64.s:1223\"\n       > time=2024-09-22T21:21:33.503+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/patchpkg/builder.go:92 msg=\"starting build to patch package\" pkg=/nix/store/r26gjy09nhlai4xwxk24v19987mamgvx-python3-3.10.15 glibc=\"\" out=/nix/store/gn3xc3n1nqf5wqy891i58mqciyajxa9y-python3-3.10.15\n       > Error: can't find hash to restore store path reference \"eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee-llvm-16.0.6\" in \"lib/python3.10/_sysconfigdata__darwin_darwin.py\": regexp \"[0123456789abcdfghijklmnpqrsvwxyz]{32}-llvm-16\\\\.0\\\\.6([$\\\"'{}/[\\\\] \\\\t\\\\r\\\\n]|$)\" returned 0 matches\n       >\n       > time=2024-09-22T21:21:33.506+02:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:70 msg=\"command error\" execid=dbc2ef7b3c4a42e899c6ce34d0a51980 stack=<nil>\n       > time=2024-09-22T21:21:33.506+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg=\"searching for config file (including parent directories)\" path=.\n       > time=2024-09-22T21:21:33.506+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=devbox.json\n       > time=2024-09-22T21:21:33.506+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:108 msg=\"trying config file\" path=.\n       > time=2024-09-22T21:21:33.506+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=/private/tmp/devbox.json\n       > time=2024-09-22T21:21:33.506+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=/private/devbox.json\n       > time=2024-09-22T21:21:33.506+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg=\"trying config file\" path=/devbox.json\n       > time=2024-09-22T21:21:33.506+02:00 level=ERROR source=go.jetpack.io/devbox/internal/devconfig/config.go:135 msg=\"config file search error\" err=\"no devbox config file found\" dur=37.542µs\n       For full logs, run 'nix-store -l /nix/store/62m57fl3nqrflknm7gi5xgjhzlzlkf7s-python3-3.10.15.drv'.\nerror: 1 dependencies of derivation '/nix/store/p3cp9f07kj5pc1l6kyjp7fclxfzv4fpm-nix-shell-env.drv' failed to build\n" execid=8978f98bf05b4d31a28b89547e8b634f stack="error running script \"mycrash.sh\" in Devbox: nix: command error: nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json path:/Users/filippomerante/project/github/test/.devbox/gen/flake: 1 dependencies of derivation '/nix/store/p3cp9f07kj5pc1l6kyjp7fclxfzv4fpm-nix-shell-env.drv' failed to build: exit code 1\ngo.jetpack.io/devbox/internal/boxcli.runScriptCmd\n\tgo.jetpack.io/devbox/internal/boxcli/run.go:127\ngo.jetpack.io/devbox/internal/boxcli.runCmd.func1\n\tgo.jetpack.io/devbox/internal/boxcli/run.go:50\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1039\ngo.jetpack.io/devbox/internal/boxcli/midcobra.(*midcobraExecutable).Execute\n\tgo.jetpack.io/devbox/internal/boxcli/midcobra/midcobra.go:61\ngo.jetpack.io/devbox/internal/boxcli.Execute\n\tgo.jetpack.io/devbox/internal/boxcli/root.go:116\ngo.jetpack.io/devbox/internal/boxcli.Main\n\tgo.jetpack.io/devbox/internal/boxcli/root.go:139\nmain.main\n\t./main.go:11\nruntime.main\n\truntime/proc.go:272\nruntime.goexit\n\truntime/asm_arm64.s:1223"
time=2024-09-22T21:21:33.535+02:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:70 msg="command error" execid=8978f98bf05b4d31a28b89547e8b634f stack="error running script \"mycrash.sh\" in Devbox: nix: command error: nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' print-dev-env --json path:/Users/filippomerante/project/github/test/.devbox/gen/flake: 1 dependencies of derivation '/nix/store/p3cp9f07kj5pc1l6kyjp7fclxfzv4fpm-nix-shell-env.drv' failed to build: exit code 1\ngo.jetpack.io/devbox/internal/boxcli.runScriptCmd\n\tgo.jetpack.io/devbox/internal/boxcli/run.go:127\ngo.jetpack.io/devbox/internal/boxcli.runCmd.func1\n\tgo.jetpack.io/devbox/internal/boxcli/run.go:50\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:983\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.8.0/command.go:1039\ngo.jetpack.io/devbox/internal/boxcli/midcobra.(*midcobraExecutable).Execute\n\tgo.jetpack.io/devbox/internal/boxcli/midcobra/midcobra.go:61\ngo.jetpack.io/devbox/internal/boxcli.Execute\n\tgo.jetpack.io/devbox/internal/boxcli/root.go:116\ngo.jetpack.io/devbox/internal/boxcli.Main\n\tgo.jetpack.io/devbox/internal/boxcli/root.go:139\nmain.main\n\t./main.go:11\nruntime.main\n\truntime/proc.go:272\nruntime.goexit\n\truntime/asm_arm64.s:1223"
time=2024-09-22T21:21:33.535+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-09-22T21:21:33.535+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-09-22T21:21:33.536+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/filippomerante/project/github/test/devbox.json dur=146µs
time=2024-09-22T21:21:33.536+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package needs patching" pkg=python mode=auto

**Comment by gcurtis** [comment]
This might be a bug in the latest release. As a workaround, could you try setting the `patch` field for Python to `never`?

```diff
{
  "$schema":  "https://raw.githubusercontent.com/jetify-com/devbox/0.13.0/.schema/devbox.schema.json",
-  "packages": ["python@3.10"]
+  "packages": {
+    "python": {
+      "version": "3.10",
+      "patch":   "never"
+    }
+  }
}
```

**Comment by filippolmt** [comment]
The thing is very strange, if I use this wording:
`{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.13.0/.schema/devbox.schema.json",
  "packages": {
    "python": {
      "version": "3.10.15",
      "patch": "never"
    }
  }
}
`
works, while if I try to add it in the classic mode:

`{
  "$schema":  "https://raw.githubusercontent.com/jetify-com/devbox/0.13.0/.schema/devbox.schema.json",
  "packages": ["python@3.10.15"]
}`

it returns the error I reported

**Comment by djgoku** [comment]
I also had a similar experience. Where `"packages": ["python@3.12"]` wasn't working and switching over to the above started the shell.

```
{
  "$schema":  "https://raw.githubusercontent.com/jetify-com/devbox/0.13.0/.schema/devbox.schema.json",
  "packages": {"python": {"version": "3.12", "patch": "never"}}
  }
}
```

**Comment by okwilkins** [comment]
I can also confirm that:

```json
{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.13.0/.schema/devbox.schema.json",
  "packages": {
    "python": {
        "version": "3.12.4",
        "patch": "never"
    }
  }
}
```

fixes the issue.

**Comment by Lagoja** [comment]
We should have a hotfix for this shortly that will let the autopatching work. I'll update this issue when it's published
