### ISSUE TITLE
Devbox shell not working correctly in tmux

### ISSUE THREAD

**Issue by robinheghan** [jetify-com/devbox#2343]
### What happened?

![Skjermbilde 2024-10-10 kl  09 26 23](https://github.com/user-attachments/assets/c07f9ba8-741a-4fb0-ae50-90a13fdf40c4)

Typing in `devbox shell` is completely broken when run in tmux. Works fine when not using tmux.

### Steps to reproduce

1. be in a tmux session
2. run `devbox shell`
3. start typing

### Command

shell

### devbox.json

```jsonc
{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.13.4/.schema/devbox.schema.json",
  "packages": [
    "nodejs@20",
    "ghc@9.4.8",
    "cabal-install@3.8.1.0"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.13.4

### Nix version

2.24.7

### What system does this bug occur on?

macOS (Apple Silicon)

### Debug logs

time=2024-10-10T09:29:22.519+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-10-10T09:29:22.519+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-10-10T09:29:22.519+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/robin/Workspace/gren/compiler/devbox.json dur=1.429708ms
time=2024-10-10T09:29:22.519+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=nodejs mode=auto
time=2024-10-10T09:29:22.519+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ghc mode=auto
time=2024-10-10T09:29:22.519+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=cabal-install mode=auto
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/robin/Workspace/gren/compiler/devbox.json dur=37.458µs
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=nodejs mode=auto
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ghc mode=auto
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=cabal-install mode=auto
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.520+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.569+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/nix.go:342 msg="nix --version --debug output" out="nix (Nix) 2.24.7\nSystem type: aarch64-darwin\nAdditional system types: x86_64-darwin\nFeatures: gc, signed-caches\nSystem configuration file: /etc/nix/nix.conf\nUser configuration files: /Users/robin/.config/nix/nix.conf:/etc/xdg/nix/nix.conf\nStore directory: /nix/store\nState directory: /nix/var/nix\nData directory: /nix/store/7mb1mcpmjphg5bgc8m7m0gxrsshrzsk7-nix-2.24.7/share\n"
time=2024-10-10T09:29:22.569+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/nix/var/nix/profiles/default/bin/nix
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/nix/var/nix/profiles/default/bin/nix cmd.pid=2768 cmd.code=0 cmd.dur=33.62425ms
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/Users/robin/Workspace/gren/compiler/devbox.json dur=110.209µs
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=nodejs mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ghc mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=cabal-install mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=nodejs mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=cabal-install mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=nodejs mode=auto
time=2024-10-10T09:29:22.603+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=cabal-install mode=auto
time=2024-10-10T09:29:22.604+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/devbox.go:697 msg="current environment PATH" path=/Users/robin/.cabal/bin:/Users/robin/.local/bin:/opt/homebrew/bin:/nix/var/nix/profiles/default/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/node@18/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/robin/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/robin/.cabal/bin:/Users/robin/.local/bin:/opt/homebrew/bin:/Users/robin/.ghcup/bin:/Users/robin/.ghcup/bin
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/devbox.go:712 msg="nix environment PATH" path=/nix/store/sa6hywsm1mqfyd1xakyzv4ljjsb3hawh-clang-wrapper-11.1.0/bin:/nix/store/ljz45vk739778lw2xaw2jvy7ihip2q07-clang-11.1.0/bin:/nix/store/943sxl4vcfpfg6xaagxvgwbgz9scl7lc-coreutils-9.3/bin:/nix/store/m488d5iwzn93bdk1j5gxl77k3zb8y285-cctools-binutils-darwin-wrapper-11.1.0-973.0.1/bin:/nix/store/x5bm27csww06snmzrsqhxfzl0i8mad5c-cctools-binutils-darwin-11.1.0-973.0.1/bin:/nix/store/hxl1k8qgmrm1vfq5f419iv4wybz9szqq-nodejs-20.17.0/bin:/nix/store/060dvanq07yffbjqqard255g3rf80npk-cabal-install-3.8.1.0/bin:/nix/store/ldgr8rqmkq941pwgi7zl80d3akil3va4-ghc-9.4.8/bin:/nix/store/iz66rbm4c48m920zjiic3sc8ghl8pvgs-ncurses-6.4/bin:/nix/store/n7hyb4xfwjdcm87gbisck8pl9c2mp1qs-libiconv-50/bin:/nix/store/943sxl4vcfpfg6xaagxvgwbgz9scl7lc-coreutils-9.3/bin:/nix/store/ngyiha629vs37hb2pwmk489ndf7nmh20-findutils-4.9.0/bin:/nix/store/d1gsih58dvmj2da2im0c5k3rz2x6zhff-diffutils-3.10/bin:/nix/store/fh1327f06qipzcnv2di22vssbbzk1hrz-gnused-4.9/bin:/nix/store/kxbn7dv0i7p0ylsbr53j7z0gf45kim78-gnugrep-3.11/bin:/nix/store/qllkm9swhw8fgs46v2mk64kl88cm7jh8-gawk-5.2.2/bin:/nix/store/fpmgc7y2dihni7kpwvgaq46fjcds6my1-gnutar-1.35/bin:/nix/store/5dyk8m2il19cm2q7bvrlvnd6957jpp6s-gzip-1.13/bin:/nix/store/722g4vgl3g935h805y7phifmdvq2xl8p-bzip2-1.0.8-bin/bin:/nix/store/5sbqambqp3w2sc5mm3b7ddgla5jp7v9a-gnumake-4.4.1/bin:/nix/store/zzpm4317hn2y29rm46krsasaww9wxb1k-bash-5.2-p15/bin:/nix/store/v2s7n510v8zf67ngj4962zjia6h25r88-patch-2.7.6/bin:/nix/store/w2hc8y9m36d2nwrvrf27yrvzpwc8pbcm-xz-5.4.4-bin/bin:/nix/store/ps2jbdzj9kxch1b77apis0i06chk91qw-file-5.45/bin
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/devbox.go:746 msg="PATH after plugins and config" path=/Users/robin/Workspace/gren/compiler/.devbox/nix/profile/default/bin:/nix/store/sa6hywsm1mqfyd1xakyzv4ljjsb3hawh-clang-wrapper-11.1.0/bin:/nix/store/ljz45vk739778lw2xaw2jvy7ihip2q07-clang-11.1.0/bin:/nix/store/943sxl4vcfpfg6xaagxvgwbgz9scl7lc-coreutils-9.3/bin:/nix/store/m488d5iwzn93bdk1j5gxl77k3zb8y285-cctools-binutils-darwin-wrapper-11.1.0-973.0.1/bin:/nix/store/x5bm27csww06snmzrsqhxfzl0i8mad5c-cctools-binutils-darwin-11.1.0-973.0.1/bin:/nix/store/hxl1k8qgmrm1vfq5f419iv4wybz9szqq-nodejs-20.17.0/bin:/nix/store/060dvanq07yffbjqqard255g3rf80npk-cabal-install-3.8.1.0/bin:/nix/store/ldgr8rqmkq941pwgi7zl80d3akil3va4-ghc-9.4.8/bin:/nix/store/iz66rbm4c48m920zjiic3sc8ghl8pvgs-ncurses-6.4/bin:/nix/store/n7hyb4xfwjdcm87gbisck8pl9c2mp1qs-libiconv-50/bin:/nix/store/ngyiha629vs37hb2pwmk489ndf7nmh20-findutils-4.9.0/bin:/nix/store/d1gsih58dvmj2da2im0c5k3rz2x6zhff-diffutils-3.10/bin:/nix/store/fh1327f06qipzcnv2di22vssbbzk1hrz-gnused-4.9/bin:/nix/store/kxbn7dv0i7p0ylsbr53j7z0gf45kim78-gnugrep-3.11/bin:/nix/store/qllkm9swhw8fgs46v2mk64kl88cm7jh8-gawk-5.2.2/bin:/nix/store/fpmgc7y2dihni7kpwvgaq46fjcds6my1-gnutar-1.35/bin:/nix/store/5dyk8m2il19cm2q7bvrlvnd6957jpp6s-gzip-1.13/bin:/nix/store/722g4vgl3g935h805y7phifmdvq2xl8p-bzip2-1.0.8-bin/bin:/nix/store/5sbqambqp3w2sc5mm3b7ddgla5jp7v9a-gnumake-4.4.1/bin:/nix/store/zzpm4317hn2y29rm46krsasaww9wxb1k-bash-5.2-p15/bin:/nix/store/v2s7n510v8zf67ngj4962zjia6h25r88-patch-2.7.6/bin:/nix/store/w2hc8y9m36d2nwrvrf27yrvzpwc8pbcm-xz-5.4.4-bin/bin:/nix/store/ps2jbdzj9kxch1b77apis0i06chk91qw-file-5.45/bin
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/devbox.go:764 msg="filtering out buildInput from PATH" path=/nix/store/hxl1k8qgmrm1vfq5f419iv4wybz9szqq-nodejs-20.17.0/bin input=/nix/store/hxl1k8qgmrm1vfq5f419iv4wybz9szqq-nodejs-20.17.0
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/devbox.go:764 msg="filtering out buildInput from PATH" path=/nix/store/060dvanq07yffbjqqard255g3rf80npk-cabal-install-3.8.1.0/bin input=/nix/store/060dvanq07yffbjqqard255g3rf80npk-cabal-install-3.8.1.0
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/devbox.go:764 msg="filtering out buildInput from PATH" path=/nix/store/ldgr8rqmkq941pwgi7zl80d3akil3va4-ghc-9.4.8/bin input=/nix/store/ldgr8rqmkq941pwgi7zl80d3akil3va4-ghc-9.4.8
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/devbox.go:770 msg="PATH after filtering buildInputs" inputs="[/nix/store/hxl1k8qgmrm1vfq5f419iv4wybz9szqq-nodejs-20.17.0 /nix/store/060dvanq07yffbjqqard255g3rf80npk-cabal-install-3.8.1.0 /nix/store/ldgr8rqmkq941pwgi7zl80d3akil3va4-ghc-9.4.8]" path=/Users/robin/Workspace/gren/compiler/.devbox/nix/profile/default/bin:/nix/store/sa6hywsm1mqfyd1xakyzv4ljjsb3hawh-clang-wrapper-11.1.0/bin:/nix/store/ljz45vk739778lw2xaw2jvy7ihip2q07-clang-11.1.0/bin:/nix/store/943sxl4vcfpfg6xaagxvgwbgz9scl7lc-coreutils-9.3/bin:/nix/store/m488d5iwzn93bdk1j5gxl77k3zb8y285-cctools-binutils-darwin-wrapper-11.1.0-973.0.1/bin:/nix/store/x5bm27csww06snmzrsqhxfzl0i8mad5c-cctools-binutils-darwin-11.1.0-973.0.1/bin:/nix/store/iz66rbm4c48m920zjiic3sc8ghl8pvgs-ncurses-6.4/bin:/nix/store/n7hyb4xfwjdcm87gbisck8pl9c2mp1qs-libiconv-50/bin:/nix/store/ngyiha629vs37hb2pwmk489ndf7nmh20-findutils-4.9.0/bin:/nix/store/d1gsih58dvmj2da2im0c5k3rz2x6zhff-diffutils-3.10/bin:/nix/store/fh1327f06qipzcnv2di22vssbbzk1hrz-gnused-4.9/bin:/nix/store/kxbn7dv0i7p0ylsbr53j7z0gf45kim78-gnugrep-3.11/bin:/nix/store/qllkm9swhw8fgs46v2mk64kl88cm7jh8-gawk-5.2.2/bin:/nix/store/fpmgc7y2dihni7kpwvgaq46fjcds6my1-gnutar-1.35/bin:/nix/store/5dyk8m2il19cm2q7bvrlvnd6957jpp6s-gzip-1.13/bin:/nix/store/722g4vgl3g935h805y7phifmdvq2xl8p-bzip2-1.0.8-bin/bin:/nix/store/5sbqambqp3w2sc5mm3b7ddgla5jp7v9a-gnumake-4.4.1/bin:/nix/store/zzpm4317hn2y29rm46krsasaww9wxb1k-bash-5.2-p15/bin:/nix/store/v2s7n510v8zf67ngj4962zjia6h25r88-patch-2.7.6/bin:/nix/store/w2hc8y9m36d2nwrvrf27yrvzpwc8pbcm-xz-5.4.4-bin/bin:/nix/store/ps2jbdzj9kxch1b77apis0i06chk91qw-file-5.45/bin
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg="" mode=auto
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=nodejs mode=auto
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=cabal-install mode=auto
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/devbox.go:789 msg="new path stack is" path_stack=DEVBOX_NIX_ENV_PATH_a6dc8ababae2e6aa9ea310af7f13f562ef34e529a8e6b7ae28c5d5f8cff253b5:DEVBOX_INIT_PATH
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/devbox.go:791 msg="computed environment PATH" path=/Users/robin/Workspace/gren/compiler/.devbox/nix/profile/default/bin:/nix/store/sa6hywsm1mqfyd1xakyzv4ljjsb3hawh-clang-wrapper-11.1.0/bin:/nix/store/ljz45vk739778lw2xaw2jvy7ihip2q07-clang-11.1.0/bin:/nix/store/943sxl4vcfpfg6xaagxvgwbgz9scl7lc-coreutils-9.3/bin:/nix/store/m488d5iwzn93bdk1j5gxl77k3zb8y285-cctools-binutils-darwin-wrapper-11.1.0-973.0.1/bin:/nix/store/x5bm27csww06snmzrsqhxfzl0i8mad5c-cctools-binutils-darwin-11.1.0-973.0.1/bin:/nix/store/iz66rbm4c48m920zjiic3sc8ghl8pvgs-ncurses-6.4/bin:/nix/store/n7hyb4xfwjdcm87gbisck8pl9c2mp1qs-libiconv-50/bin:/nix/store/ngyiha629vs37hb2pwmk489ndf7nmh20-findutils-4.9.0/bin:/nix/store/d1gsih58dvmj2da2im0c5k3rz2x6zhff-diffutils-3.10/bin:/nix/store/fh1327f06qipzcnv2di22vssbbzk1hrz-gnused-4.9/bin:/nix/store/kxbn7dv0i7p0ylsbr53j7z0gf45kim78-gnugrep-3.11/bin:/nix/store/qllkm9swhw8fgs46v2mk64kl88cm7jh8-gawk-5.2.2/bin:/nix/store/fpmgc7y2dihni7kpwvgaq46fjcds6my1-gnutar-1.35/bin:/nix/store/5dyk8m2il19cm2q7bvrlvnd6957jpp6s-gzip-1.13/bin:/nix/store/722g4vgl3g935h805y7phifmdvq2xl8p-bzip2-1.0.8-bin/bin:/nix/store/5sbqambqp3w2sc5mm3b7ddgla5jp7v9a-gnumake-4.4.1/bin:/nix/store/zzpm4317hn2y29rm46krsasaww9wxb1k-bash-5.2-p15/bin:/nix/store/v2s7n510v8zf67ngj4962zjia6h25r88-patch-2.7.6/bin:/nix/store/w2hc8y9m36d2nwrvrf27yrvzpwc8pbcm-xz-5.4.4-bin/bin:/nix/store/ps2jbdzj9kxch1b77apis0i06chk91qw-file-5.45/bin:/Users/robin/Workspace/gren/compiler/.devbox/virtenv/runx/bin:/Users/robin/.cabal/bin:/Users/robin/.local/bin:/opt/homebrew/bin:/nix/var/nix/profiles/default/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/node@18/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/robin/.asdf/shims:/opt/homebrew/opt/asdf/libexec/bin:/Users/robin/.ghcup/bin
Starting a devbox shell...
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/shell.go:102 msg="using SHELL env var for shell binary path" shell=/opt/homebrew/bin/fish
time=2024-10-10T09:29:22.605+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/shell.go:86 msg="detected user shell" shell=/opt/homebrew/bin/fish initrc=/Users/robin/.config/fish/config.fish
time=2024-10-10T09:29:22.606+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/shell.go:346 msg="wrote devbox shellrc" path=/var/folders/c3/ksj1yh_96b7_k78mzgw7k5xr0000gn/T/devbox2186296180/config.fish
time=2024-10-10T09:29:22.606+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devbox/shell.go:247 msg="Executing shell %s with args: %v" /opt/homebrew/bin/fish="[/opt/homebrew/bin/fish -C . /var/folders/c3/ksj1yh_96b7_k78mzgw7k5xr0000gn/T/devbox2186296180/config.fish]"

**Comment by DerArkeN** [comment]
What version of tmux are you using (tmux -V). I also noticed you are using fish, have you tried any other shell?
I am using tmux 3.5 with the newest devbox version in zsh every day without a problem on WSL2.

**Comment by robinheghan** [comment]
tmux 3.5a.

Interesting. If I run `devbox shell` and then start tmux, everything works fine 🤷 
If i run `devbox shell` and then execute `zsh`, everything works fine. Exiting from `zsh`, which drops me back to a devbox shell in fish, it's still wonky.

**Comment by DerArkeN** [comment]
In your debug file the fish shell starts like this
`msg="Executing shell %s with args: %v" /opt/homebrew/bin/fish="[/opt/homebrew/bin/fish -C .`
isn't -C preventing rc files from running or am I wrong?
what happens if you 
1. start tmux
2. devbox shell
3. fish
4. start typing
?

**Comment by Lagoja** [comment]
That is one of the weirdest errors I've seen... I've tried reproducing it a few different ways but can't get it to repro on my machine. Just to gather some more data: 

1. What terminal emulator are you using?
2. Does the same error happen if you temporarily move/delete your fish config?

**Comment by robinheghan** [comment]
@DerArkeN starting `fish` from within devbox shell gave me the same problem

@Lagoja 1. iTerm2, but same problem with built-in Terminal.app
2. Yes

**Comment by robinheghan** [comment]
Nevermind!

Seems to be something wrong with how my prompt is configured. Thanks for your help, sorry for the noise.
