### ISSUE TITLE
Postgresql service not shutting down (process-compose hangs)

### ISSUE THREAD

**Issue by carlotm** [jetify-com/devbox#2354]
### What's happening

The postgresql service does not shut down correctly.
The `process-compose` TUI hangs forever when trying to quit. 
The postgresql os processes are kept running if you kill the process-compose terminal.

### What to expect

If you press `F10` the postgresql service should shut down correctly.

### Steps to reproduce

1. Create a new devbox shell env
2. Install `glibcLocales` if needed, and `postgresql`
3. Run `devbox services up`
4. Wait for postgresql to be ready
5. Try to stop the server with `F10` which also quits the TUI

### Command

services

### devbox.json

```jsonc
{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.13.4/.schema/devbox.schema.json",
  "packages": {
    "glibcLocales": {
      "version":   "latest",
      "platforms": ["x86_64-linux", "aarch64-linux"]
    },
    "postgresql": "latest"
  },
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.13.4

### What system does this bug occur on?

Linux (x86-64)

**Comment by behzade** [comment]
my current workaround is this script
`
{
    "scripts": {
        "down": [
            "pg_ctl stop -m fast",
            "devbox services stop"
        ]
    }
}
`

**Comment by carlotm** [comment]
@behzade  that works. Thanks.

**Comment by carlotm** [comment]
Maybe related to https://github.com/F1bonacc1/process-compose/issues/258

**Comment by Lagoja** [comment]
@carlotm Doing some testing with this, I think the best option is to revert process-compose to 1.24.2 until there is a fix on the process-compose side. I'm seeing the same issue, but can't create a process-compose.yaml that reliably circumvents it

**Comment by carlotm** [comment]
@Lagoja thanks for testing.

Dumb question:
can I downgrade just process-compose? Installing an older version in a shell does not seem to work, it always picks up 1.34.0

**Comment by Lagoja** [comment]
New release is out at 0.13.5 that reverts process-compose back to 1.24.2. Can you verify that fixes the issue?

@carlotm, we don't currently support it, but this issue makes me think we should have some override. An issue is that letting users override the version of process-compose they want to use may break some Devbox features, so we'd probably want a minimum version requirement somewhere.

**Comment by carlotm** [comment]
@Lagoja The new version fixes, thank you!

@Lagoja maybe a new key in the json schema for the process-compose version?
