### ISSUE TITLE
numpy: Error importing numpy: you should not try to import numpy from

### ISSUE THREAD

**Issue by trya2l** [jetify-com/devbox#2368]
### What happened?

Hi,

Basically, I can't seem to work with numpy under devbox. Until now I've tried using poetry, venv, python(3.12,3.11,3.10) and the issue persist.

### Steps to reproduce

1. create a devbox python environment
`devbox init && devbox generate direnv && devbox add python`
2. install dependencies
`pip install -r requirements`
4. run script that requires numpy
`python script.py`

### devbox.json

```jsonc
{
  "$schema":  "https://raw.githubusercontent.com/jetify-com/devbox/0.10.7/.schema/devbox.schema.json",
  "packages": ["python@latest"],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null",
      ". $VENV_DIR/bin/activate"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.10.7

### Nix version

nix (Nix) 2.18.5

### What system does this bug occur on?

Linux (x86-64)

### Debug logs

```shell
Traceback (most recent call last):
  File "/home/user/documents/learning/python/pca/pca.py", line 1, in <module>
    import pandas as pd
  File "/home/user/documents/learning/python/.devbox/virtenv/python/.venv/lib/python3.10/site-packages/pandas/__init__.py", line 19, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

**Comment by weilbith** [comment]
@trya2l how did you resolve this issue?

**Comment by weilbith** [comment]
Interesting. I'm on version `0.13.6` and have this issue. 🤔 
Would mind sharing a minimal setup (`devbox.json`, `pyproject.toml`, ...) that works for you? 😃

**Comment by trya2l** [comment]
Hi, sorry, I don't really have the time to go back on this issue right now, but you could have a look at https://github.com/jetify-com/devbox/issues/2370. It may be connected to your problem in some way.

**Comment by weilbith** [comment]
Okay, thanks for your help anyhow! I'll see if I can find anything and (hopefully remind to) post it here.

**Comment by gcurtis** [comment]
@weilbith I can help you debug if you open an issue with your devbox.json and any logs.

**Comment by cprice11** [comment]
Quick note for anyone who finds this like I did. Make sure you are using the recommended install methods for python or your python environment tools. I was using `pipenv` and running into this issue because I didn't also include python in my `devbox.json` file like the template does. Just specifying `pipenv` will supply python but it will cause this exact error. 

Removing `.devbox/`, `.venv/`, and lockfiles, as well as adding python properly with `devbox add python` cleared my issue up in `0.14.2`.
