### ISSUE TITLE
Error: .... context deadline exceeded when executing devbox shell.

### ISSUE THREAD

**Issue by Abdullah-AlAttar** [jetify-com/devbox#2376]
### What happened?

as the title said, I am on WSL. 
➜  ~ devbox shell
Info: Ensuring packages are installed.
Error: Head "https://cache.nixos.org/4zpmpdvkgcfgj7xnmgczj9idkpfy082m.narinfo": context deadline exceeded

### Steps to reproduce

1.
2.
3.

### Command

shell

### devbox.json

```jsonc
{
  "$schema": "https://raw.githubusercontent.com/jetify-com/devbox/0.13.5/.schema/devbox.schema.json",
  "packages": [
    "go@latest",
    "gum@latest",
    "jq@latest",
    "k9s@latest",
    "kind@latest",
    "kluctl@latest",
    "ko@latest",
    "kubectl@latest",
    "kubectx@latest",
    "kubernetes-helm@latest",
    "yq-go@latest",
    "kubent@latest",
    "fd@latest",
    "ripgrep@latest"
  ],
  "shell": {
    "init_hook": [
      "echo 'Welcome to devbox!' > /dev/null"
    ],
    "scripts": {
      "test": [
        "echo \"Error: no test specified\" && exit 1"
      ]
    }
  }
}
```

### Devbox version

0.13.5

### Nix version

nix (Nix) 2.24.7

### What system does this bug occur on?

Linux (x86-64)

### Debug logs

time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/home/ab_dullah/devbox.json dur=206.961µs
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=go mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=gum mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=jq mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=k9s mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kind mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kluctl mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ko mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectl mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectx mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubernetes-helm mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=yq-go mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubent mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=fd mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ripgrep mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/home/ab_dullah/devbox.json dur=53.449µs
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=go mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=gum mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=jq mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=k9s mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kind mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kluctl mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ko mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectl mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectx mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubernetes-helm mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=yq-go mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubent mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=fd mode=auto
time=2024-10-23T10:57:23.717+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ripgrep mode=auto
time=2024-10-23T10:57:23.736+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/nix.go:342 msg="nix --version --debug output" out="nix (Nix) 2.24.7\nSystem type: x86_64-linux\nAdditional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux, x86_64-v4-linux\nFeatures: gc, signed-caches\nSystem configuration file: /etc/nix/nix.conf\nUser configuration files: /home/ab_dullah/.config/nix/nix.conf:/etc/xdg/nix/nix.conf\nStore directory: /nix/store\nState directory: /nix/var/nix\nData directory: /nix/store/s429drnj3jp5dbxib74r3q0rypknvw48-nix-2.24.7/share\n"
time=2024-10-23T10:57:23.736+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/home/ab_dullah/.nix-profile/bin/nix
time=2024-10-23T10:57:23.754+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' eval --impure --raw --expr builtins.currentSystem" cmd.path=/home/ab_dullah/.nix-profile/bin/nix cmd.pid=14919 cmd.code=0 cmd.dur=18.695223ms
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/home/ab_dullah/devbox.json dur=98.217µs
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=go mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=gum mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=jq mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=k9s mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kind mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kluctl mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ko mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectl mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectx mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubernetes-helm mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=yq-go mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubent mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=fd mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ripgrep mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=go mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=gum mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=jq mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=k9s mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kind mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kluctl mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ko mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectl mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectx mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubernetes-helm mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=yq-go mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubent mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=fd mode=auto
time=2024-10-23T10:57:23.755+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ripgrep mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=go mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=gum mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=jq mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=k9s mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kind mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kluctl mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ko mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectl mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectx mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubernetes-helm mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=yq-go mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubent mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=fd mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ripgrep mode=auto
Info: Ensuring packages are installed.
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=go mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=gum mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=jq mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=k9s mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kind mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kluctl mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ko mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectl mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectx mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubernetes-helm mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=yq-go mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubent mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=fd mode=auto
time=2024-10-23T10:57:23.756+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ripgrep mode=auto
time=2024-10-23T10:57:32.335+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:60 msg="nix command starting" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' store info --store daemon --json" cmd.path=/home/ab_dullah/.nix-profile/bin/nix
time=2024-10-23T10:57:32.351+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/nix/command.go:67 msg="nix command exited" cmd.args="nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' store info --store daemon --json" cmd.path=/home/ab_dullah/.nix-profile/bin/nix cmd.stderr="cannot connect to socket at '/nix/var/nix/daemon-socket/socket': No such file or directory" cmd.pid=14991 cmd.code=1 cmd.dur=16.154986ms
time=2024-10-23T10:57:32.351+02:00 level=ERROR source=go.jetpack.io/devbox/internal/devbox/providers/nixcache/setup.go:81 msg="nixcache: skipping setup: error connecting to nix daemon, assuming single-user install" err="command nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' store info --store daemon --json: nix: command error: nix --extra-experimental-features ca-derivations --option experimental-features 'nix-command flakes fetch-closure' store info --store daemon --json: cannot connect to socket at '/nix/var/nix/daemon-socket/socket': No such file or directory: exit code 1: error: cannot connect to socket at '/nix/var/nix/daemon-socket/socket': No such file or directory\n"
Error: Head "https://cache.nixos.org/a125hv1m7c37b831c9pqypq867rs6ljm.narinfo": context deadline exceeded

time=2024-10-23T10:57:37.360+02:00 level=ERROR source=go.jetpack.io/devbox/internal/boxcli/midcobra/debug.go:70 msg="command error" execid=95211056007e4569a9e4499962a3ba09 stack=<nil>
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:125 msg="searching for config file (including parent directories)" path=.
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:146 msg="trying config file" path=devbox.json
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devconfig/config.go:133 msg="config file found" path=/home/ab_dullah/devbox.json dur=155.671µs
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=go mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=gum mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=jq mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=k9s mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kind mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kluctl mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ko mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectl mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubectx mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubernetes-helm mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=yq-go mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=kubent mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=fd mode=auto
time=2024-10-23T10:57:37.361+02:00 level=DEBUG source=go.jetpack.io/devbox/internal/devpkg/package.go:200 msg="package doesn't need patching" pkg=ripgrep mode=auto

**Comment by DerArkeN** [comment]
does this happen every time or occasionally? have you tried doing a full reboot of wsl?
try in powershell:
```
wsl --shutdown
wsl
```

**Comment by Lagoja** [comment]
Hey @Abdullah-AlAttar, 

This is usually caused by network issues, where Devbox + Nix is unable to download the `.narinfo` file from the Nix cache before a timeout. 

We're working on better error messaging and handling for this, but in the meantime I would recommend checking your connection, or retrying the download.

**Comment by jaitaiwan** [comment]
I'm gettting this issue currently where the timeout is 5s hardcoded in devbox but the curl requests to the same are taking just over 10s

This has been consistent for the last 8 hours
