### ISSUE TITLE
Allow direnv to be installed via Devbox for integration

### ISSUE THREAD

**Issue by kpervin** [jetify-com/devbox#2412]
### What problem are you trying to solve?

Currently we need to install `direnv` outside of `devbox.json` for `direnv` to work. However, that seems antithetical to the entire purpose of devbox, as it means team members need to individually install `direnv` for it to work.

### What solution would you like?

Add the means for `devbox generate direnv` to install `direnv` in `devbox.json` and then use that binary for all subsequent work.

**Comment by drewgingerich** [comment]
As somewhat of a workaround, I am installing `direnv` with Devbox at the global level:

```sh
devbox global add direnv
```

This way `direnv' can be used for project-level stuff while still being managed by Devbox in some form. The global `devbox.json` and `devbox.lock` can be shared around the organization to complete the goal of consistent development environments for everyone.
