### ISSUE TITLE
Inheritance

### ISSUE THREAD

**Issue by vfarcic** [jetify-com/devbox#2424]
### What problem are you trying to solve?

Typically, I have two `devbox.json` files. One with all the tools I need to work on a project, and another to workflows (e.g., GitHub Actions). The latter contains a subset of the packages in order to speed up the download process. It would be great if a devbox.json can reference packages from a different JSON file. That way I would not have to maintain the same packages in both.

### What solution would you like?

Some kind of `include` instruction that would add packages defined in a different JSON file.

**Comment by savil** [comment]
@vfarcic thanks for creating the issue. Could you have a look at the include option in Devbox.json, and the related plugin pages. I think what you desire could be achieved by considering one of your Devbox-jsons as a local plugin to include

https://www.jetify.com/docs/devbox/configuration/#include

**Comment by vfarcic** [comment]
I'm not sure I understand how I could do that with `include`. Here's an example of what I have in mind.

devbox1.json
```json
{
  "packages": [
    "kind@0.22.0",
    "gh@2.44.1",
    "kubectl@1.29.2",
    "bat@0.24.0",
    "upbound@0.24.1",
    "kubernetes-helm@3.14.1",
    "watchexec@1.25.1",
    "kyverno-chainsaw@0.2.5",
    "just@1.30.1",
    "jq@1.7.1"
  ],
  "shell": {
    "init_hook": [],
    "scripts": {}
  }
}
```

devbox2.json
```json
{
  "packages": [
    "just@1.30.1",
    "jq@1.7.1"
  ],
  "shell": {
    "init_hook": [],
    "scripts": {}
  }
}
```

`just` and `jq` are in both files so devbox1.json is a superset of `devbox2.json`. What I'm trying to do is include all the `packages` from `devbox2.json` into `devbox1.json` to avoid defining the same set of packages in both. Could I do that with `include`? If I could, do you have an example?

**Comment by DerArkeN** [comment]
just use devbox global for that, no?
https://www.jetify.com/docs/devbox/devbox_global/

**Comment by vfarcic** [comment]
Both files are used in a project and are supposed to be available to everyone working on that project. Besides, the main reason for such a separation is so that workflows (e.g., GitHub Actions) install packages faster. That's one one is a subset of the other (it has only what's needed in workflows).

**Comment by savil** [comment]
@vfarcic we were away for the Thanksgiving break in the US. 

Please have a look at https://github.com/jetify-com/devbox-issue-2424 
Does that address your scenario?

**Comment by vfarcic** [comment]
Not quite... `include` has to be a directory with `plugin.json`. That's not a problem by itself since I can execute something like `devbox shell --config `PATH_TO_PLUGINS_DIR`. However, when using it with Devbox GitHub Actions extension, I would have something like this.

```yaml
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          project-path: devbox-plugin/plugin.json
```

As a result, that would change the context to a different dir and, on top of that, still use `devbox.json` in the project's root.

**Comment by savil** [comment]
@vfarcic I see. One clarification, I don't think you can use a plugin.json as a replacement for the devbox.json. They have a similar schema but do differ slightly.

My suggestion is:
- devbox.json for tools
- devbox.json for workflows
- plugin.json for common packages; this plugin is included by both devbox.jsons

Does that work?

**Comment by vfarcic** [comment]
It's a bit of a weird workaround, but it works.

**Comment by weilbith** [comment]
Hi 👋 

I've a different use case that is nagging me quite a while already. If a project/repository uses Devbox, there is already a `devbox.json` configuration. But quite often, I need to extend the listed dependencies for my local work. Like I wanna have some language servers or debuggers installed. Dependencies that are possibly not of interest for the majority of the people working in the repository (e.g. because they work with a Jetbrains IDEs). I would love to add a local `devbox.json` and add it to `.git/info/exclude`.

I've seen that alternatives like devenv and Flox have solutions for this. I'm tempted to try them (in combination?). However, though I might just ask again for some feedback here.

Thank you!
