### ISSUE TITLE
[Bug]: devbox add fails if path to current dir contains spaces

### ISSUE THREAD

**Issue by exister** [jetify-com/devbox#971]
**Current Behavior (bug)**

if current path has any spaces in it, ex `/path/to/project dir/`, devbox fails with internal error.

**Expected Behavior (fix)**
spaces are handled correctly

**Additional context**
Version:     0.4.8
Platform:    darwin_amd64
Commit:      9645d483100224e3255105da1d6a536efca23105
Commit Time: 2023-04-19T18:11:07Z
Go Version:  go1.20.3

**Comment by hezhizhen** [comment]
Can you provide a detailed example to re-produce it? Thanks.

Normally there would be a `\` like `/path/to/project\ dir/` for space.

**Comment by hezhizhen** [comment]
I have re-produced it.

**Comment by hezhizhen** [comment]
It seems a known issue in Nix: https://github.com/NixOS/nix/issues/6394

**Comment by Lagoja** [comment]
This should now be fixed in [Devbox 0.13.1](https://github.com/jetify-com/devbox/releases/tag/0.13.1)
